sudo: required
language: node_js
before_script:
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-auto-update/DEBIAN/control
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-auto-update/usr/local/bin/magic-package-auto-update
script:
- dpkg-deb --build magic-package-auto-update
deploy:
  matrix:
  - provider: packagecloud
    repository: magic-package-beta
    username: krack
    token:
      secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
    dist: ubuntu/xenial
    skip_cleanup: true
    on:
      tags: false
  - provider: packagecloud
    repository: magic-package-beta
    username: krack
    token:
      secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
    dist: ubuntu/yakkety
    skip_cleanup: true
    on:
      tags: false
  - provider: packagecloud
    repository: magic-package
    username: krack
    token:
      secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
    dist: ubuntu/xenial
    skip_cleanup: true
    on:
      tags: true
  - provider: packagecloud
    repository: magic-package
    username: krack
    token:
      secure: hxcBAw8Jkp1ppHRA7VrmJ0ZS2Z9cj0QGqh67KgiIiSoN4YH8NaZpMhdaK+kw7GLzb39vzSb9DQy28+O+YMpqLRPWmRG7Matx12fBJw2diQj2DlX9nHoI2A3UAJ2ZRrbCGg1pJo1z921RioC4326Ym6voxhvGfny0X18Urr2fIKXrMeGys+6d3jblDx7NabVRtOkKcq9AtVCnWv55WYWvBMqci7fhcxQDS2D0TtA4Bl/aohg2G5/D5TnkEv/DIMJOSPAyK9gC8ryvZKte+t/fovMKKuVms6LczIqI466KciRVd2I56w8fVFlLb6NCRLOfVO/rZ3rd6EdG72aG1riK+CGu6UWpLbeiDvHWW+ktWgWTqfPXpSkwUtl/l/TFKqMXgRKQX/KP0vjxtgtN+qhvt9ZOwsG6qKotsDIkVh0RU/GeOxUfHZ4zc7nBHr+Sw//axSuw1vSoL5wLTpWIaHEcpYdSj4FWp00wjE/c1K0M4+MyVlsYML6Z3MM42LLJpGWUUm9Y20n7cCx417ne1azhPifTgP9wACpKfuq1VkKKBSeTYan6kh5N63aQnOGUKLP+v6rEFsXZwsiWr2nXY+fbEA4nsbPm4LDQR9Yojdj76vCy2FGJsnJ6T91GCPQ4rlOYzqNvUc2jYD83qGkQYjZYU6Y02gtp7NGyfPPl87aEAYg=
    dist: ubuntu/yakkety
    skip_cleanup: true
    on:
      tags: true
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
