sudo: required
language: node_js
before_script:
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-auto-update/DEBIAN/control
- sed -i 's/$TRAVIS_TAG/'${TRAVIS_TAG:-${TRAVIS_JOB_NUMBER:-0}}'/g' ./magic-package-auto-update/usr/local/bin/magic-package-auto-update
script:
- dpkg-deb --build magic-package-auto-update
deploy:
- provider: packagecloud
  repository: magic-package-beta
  username: krack
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
  dist: ubuntu/disco
  skip_cleanup: true
  on:
    tags: false
- provider: packagecloud
  repository: magic-package-beta
  username: krack
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
  dist: ubuntu/bionic
  skip_cleanup: true
  on:
    tags: false
- provider: packagecloud
  repository: magic-package-beta
  username: krack
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
  dist: ubuntu/cosmic
  skip_cleanup: true
  on:
    tags: false
- provider: packagecloud
  repository: magic-package
  username: krack
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
  dist: ubuntu/disco
  skip_cleanup: true
  on:
    tags: true
- provider: packagecloud
  repository: magic-package
  username: krack
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
  dist: ubuntu/bionic
  skip_cleanup: true
  on:
    tags: true
- provider: packagecloud
  repository: magic-package
  username: krack
  token:
    secure: cpVFzmXIYZYGKOR0pDk46kX6JpzPayvR5sQdUzjMMEYZBSnb3kAji6pXc8qeo5mBgwPYBUUqLBMeXMDMSj9H+hOFNM9Cbe8cMHbVyZY/Ci4kbg0KJcs7FMSd+YEbZTPgMI8fpJ220gpRzk9GNk+gtwPcQFO1zVyXfjDc24RrKyrW9cmef3qKs68JoRjfTz8HI589uLkBpAPR5QV5U9X4sZJl71OS2u4Dczq2EciHSRrKRijhiq/5YKoQryUKaU17V98S1NuSv7qPG6PorvC4igbo8pV8IL8bDALs7MYKsYETf/gZTsKTO6krkwJZ76VAC+4Vmga0BdEM21Gymg6XtFuRqspPjN6cb61KDZJYypvJhQVosaQr5X1eELNwbNCJxNl1AN+jKLRjw06vjmWzug0GGXb4JCB5hskNjBPzLaP1ftSfK4pb5navTvGvNkWUj6ONB4hu0B+7JaYfNWqfS2wsjjCadj2e1B8TSugulo2FUOStub5Veu4kZ8iojBSReE2LOTcUEqb7rHTnjeQ50CCGwkd7Gx9UThnt3REWS216kC7z0JXb/p1EnNZ7PD6jekE7RlrtirtLlDM7CzbhwoS3KOuB7eT0V3RRgctfmQwFyCq+P56qIvhl34fyyM45RVfKeGIxSJyeEqXSylDe32SzHlMbGhRumvQS2FKFW7U=
  dist: ubuntu/cosmic
  skip_cleanup: true
  on:
    tags: true
