#!/bin/bash


#on ajoute la ligne pour mettre à jour toutes les 3h s'il n'est pas déjà présent
if ! grep -q "14 \*/3 \* \* \*" /etc/cron.d/cron-apt; then
	echo "14 */3 * * *	root	test -x /usr/sbin/cron-apt && /usr/sbin/cron-apt" >> /etc/cron.d/cron-apt
	echo "Added  upgrade software done"
fi

echo "install done"



